[package]
name = "wasmre"
version = "0.1.0"
edition = "2021"

[dependencies]
code_highlighter = "0.1.1"
serde = { version = "1.0.204", features = ["derive"] }
clap = { version = "4.5.9", features = ["derive"] }
